#' cusum_control_plot
#'
#' @param df input data frame generated by cusum_control function
#' @param title_text optional title for chart
#'
#' @return ggplot2 object suited for further customisation
#'
#' @importFrom rlang .data
#'
#' @export
#'
#' @examples
#' test_vec3 <- c(1,1,2,3,5,7,11,7,5,7,8,9,5)
#' controls <- cusum_control(test_vec3, target = 4)
#' cusum_control_plot(controls)
#'
cusum_control_plot <- function(df, do_facet = TRUE, title_text = NULL) {

  p <- ggplot2::ggplot(df,ggplot2::aes(x = .data$obs, y = .data$cplus, group = 1)) +
    ggplot2::geom_line(colour = "#000099") +
    ggplot2::geom_point(colour = "#000099")

  p <- p + ggplot2::geom_line(ggplot2::aes(.data$obs, .data$cneg))
  p <- p + ggplot2::geom_point(ggplot2::aes(.data$obs, .data$cneg))
  p <- p + ggplot2::geom_line(ggplot2::aes(.data$obs, .data$ucl),colour = "red")
  p <- p + ggplot2::geom_line(ggplot2::aes(.data$obs, .data$lcl),colour = "red")
  p <- p + ggplot2::geom_line(ggplot2::aes(.data$obs, .data$centre), colour = "grey50")
  p <- p + ggplot2::theme_minimal()
  p <- p + ggplot2::theme(panel.grid.major = ggplot2::element_blank(),
                          panel.grid.minor = ggplot2::element_blank())
  p <- p + ggplot2::labs(title = title_text, x = NULL, y = NULL)

  if (do_facet) {
    p <- p + ggplot2::facet_wrap(~.data$.id)
  }

  p
}
